# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://holofox.github.io/holofox.ru/"

theme = "congo"
defaultContentLanguage = "ru"

enableRobotsTXT = true
summaryLength = 0

[pagination]
pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]
