languageCode = "en-us"
languageName = "English (US)"
languageDirection = "ltr"
contentDir = 'content/en'
weight = 1
title = "Holofox"
copyright = "&copy; 2024 Holofox"

[params]
  displayName = "English"
  description = "Flutter development"
  isoCode = "en-US"
  dateFormat = "2 January 2006"

[params.author]
  name = "Danil Abdrafikov"
  image = "img/author.jpg"
  headline = "I Love creating, designing and developing."
  bio = "Danil came to cross-platform development after delving into native, at the same time, he was lucky enough to work with many common design patterns, which ultimately made it possible to share different knowledge profiles on building supported, flexible and reliable solutions."
  links = [
    { email = "mailto:founder@holofox.ru" },
    { github = "https://github.com/holofox" },
    { telegram = "https://t.me/horofox" },
  ]
