languageCode = "ru-ru"
languageName = "Русский (RU)"
languageDirection = "ltr"
contentDir = 'content/ru'
weight = 1
title = "Holofox"
copyright = "&copy; 2026 Holofox"

[params]
  displayName = "Russian"
  description = "Разработка на Flutter"
  isoCode = "ru-RU"
  dateFormat = "02.01.2006"
  mainSections = ["articles"]

[params.author]
  name = "Данил Абдрафиков"
  image = "img/author.jpg"
  headline = "Мне нравится представлять, творить и воплощать."
  bio = "Данил пришёл в кроссплатформенную разработку после углубления в нативную, вместе с тем, ему посчастливилось поработать со многими распространёнными паттернами проектирования, что, в конечном итоге, дало возможность делиться разными профилем знаний по постройке поддерживаемых, гибких и надёжных решений."
  links = [
    { email = "mailto:founder@holofox.ru" },
    { github = "https://github.com/holofox" },
    { telegram = "https://t.me/horofox" },
  ]
