languageCode = "ru-ru"
languageName = "Русский (RU)"
contentDir = 'content/ru'
weight = 2
title = "Holofox"
copyright = "&copy; 2024 Holofox"

[params]
  displayName = "Russian"
  description = "Flutter development"
  isoCode = "ru-RU"
  dateFormat = "2 January 2006"
  rtl = false

[params.author]
  name = "Данил Абдрафиков"
  image = "img/author.jpg"
  headline = "Мне нравится представлять, творить и воплощать."
  bio = "Данил пришёл в кроссплатформенную разработку после углубления в нативную, вместе с тем, ему посчастливилось поработать со многими распространёнными паттернами проектирования, что, в конечном итоге, дало возможность делиться разными профилем знаний по постройке поддерживаемых, гибких и надёжных решений."
  links = [
    { email = "mailto:founder@holofox.ru" },
    { github = "https://github.com/holofox" },
    { telegram = "https://t.me/horofox" },
  ]
